### ISSUE TITLE
Domanda su scopo della libreria

### ISSUE THREAD

**Issue by maxbale** [claudiopizzillo/DocumentoCommerciale.NET#1]
Buongiorno,
la sua soluzione permette dunque di emettere documenti commerciali bypassando la necessità di un RT hardware? L'AdE ha messo a disposizione delle API ufficiali per l'invio dei corrispettivi telematici esclusivamente via software?
Grazie

**Comment by claudiopizzillo** [comment]
1) Si lo permette.
2) L'AdE non ha reso disponibile alcuna API ufficiale ancora.
3) La libreria, come da risposta ad [interpello](https://www.agenziaentrate.gov.it/portale/documents/20143/2665720/Risposta+n.+413+del+25+settembre+2020.pdf/35bddf23-25e5-0aa8-49f0-ed7703230c04), è legalmente utilizzabile.
